resources:
- name: git-repo
  type: git
  source:
    uri: https://github.com/Kleppa/DevOpsExercise1
    branch: master

jobs:
- name: job-build-and-verify
  plan:
    - get: git-repo
      trigger: true
    - task: build-and-verify
      run:
        path: bash
        args: [git-repo/excersise1/ci/mvn-build.yml]